#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'saz-ssh', '>=4'
mod 'puppet-unattended_upgrades'
mod 'puppetlabs-firewall'
mod 'puppetlabs-ntp'
# Resolve deprecation warnings; https://github.com/petems/petems-swap_file/pull/81
mod 'petems/swap_file',
  :git => 'https://github.com/jtreminio/petems-swap_file.git',
  :ref => 'a497b192d0cbeaab754448caffda51ffbe9fbbfb'

mod 'puppetlabs-stdlib'
mod 'puppet-nginx', '0.15.0'
mod 'puppetlabs-vcsrepo'
mod 'thias-php'
mod 'puppetlabs-mysql'
mod 'example42-network'
# pin for https://github.com/puppetlabs/puppetlabs-docker/issues/689
mod 'puppetlabs-docker', '>=3.13.0'
# pin for puppet4+ compat
mod 'KyleAnderson/consul', '>=3.0.0'
mod 'puppet/collectd'
# pin for puppet4+ compat
mod 'datacentred/telegraf', '>=2.0.0',
  # until 2.0.0 is available from puppet forge.
  :git => 'https://github.com/yankcrime/puppet-telegraf.git',
  :ref => '2.0.0'
mod 'puppetlabs-haproxy',
  :git => 'https://github.com/aequitas/puppetlabs-haproxy.git',
  :branch => 'master'
mod 'saz/sudo'

mod 'aequitas/letsencrypt',
  :git => 'https://github.com/aequitas/puppet-letsencrypt.git',
  :ref => '052151e64f068a30c0c43df1e563e1bc69a34975'
mod 'aequitas/sites',
  :git => 'https://github.com/aequitas/puppet-sites.git',
  :ref => '04e6c2ddbcb38af011dc69eedf9cb28135c61d31'

mod 'simp/simplib'
mod 'leinaddm/htpasswd'
